// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbQgHD65hUjYemYdCEPrgbEf5HV2x8tUY',
    appId: '1:403932314326:web:f2a0e09f1e460deab66777',
    messagingSenderId: '403932314326',
    projectId: 'httplearning-50c6a',
    authDomain: 'httplearning-50c6a.firebaseapp.com',
    databaseURL: 'https://httplearning-50c6a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'httplearning-50c6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2pML3U5aKGdp9-dNiU-9age7o5VhVRbY',
    appId: '1:403932314326:ios:db0bcbf1e7ab2975b66777',
    messagingSenderId: '403932314326',
    projectId: 'httplearning-50c6a',
    databaseURL: 'https://httplearning-50c6a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'httplearning-50c6a.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2pML3U5aKGdp9-dNiU-9age7o5VhVRbY',
    appId: '1:403932314326:ios:db0bcbf1e7ab2975b66777',
    messagingSenderId: '403932314326',
    projectId: 'httplearning-50c6a',
    databaseURL: 'https://httplearning-50c6a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'httplearning-50c6a.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
}
